[project]
name = "gptapigateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faststream[cli,kafka]>=0.5.39",
    "httpx>=0.28.1",
    "pydantic-settings==2.9.1",
]
